steps:
#build stage
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sep6-ng-app-image', 'sep6-app/' ]

#push he container image to Container Registry:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/sep6-ng-app-image']

#deploy stage:
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'ng-app-docker', '--image', 'gcr.io/$PROJECT_ID/sep6-ng-app-image:latest', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']

images:
    - 'gcr.io/$PROJECT_ID/sep6-ng-app-image'