steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sep6-ng-app-image', 'sep6-app/' ]
      
#deploy stage

    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'cloudrunservice', '--image', 'gcr.io/$PROJECT_ID/sep6-ng-app-image', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

      images:
    - 'gcr.io/$PROJECT_ID/sep6-ng-app-image'



