steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sep6-ng-app-image:latest', 'sep6-app/' ]

#deploy stage

    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'ng-app-docker', '--image', 'gcr.io/$PROJECT_ID/sep6-ng-app-image:latest', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']

images:
    - 'gcr.io/$PROJECT_ID/sep6-ng-app-image:latest'



